/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ContainerSchema extends BaseModel {
  static $columns = ['categoryIndentifier', 'checkDigit', 'createdAt', 'id', 'ownerCode', 'serialNumber', 'sizeType', 'typeGroup', 'updatedAt'] as const
  $columns = ContainerSchema.$columns
  @column()
  declare categoryIndentifier: string
  @column()
  declare checkDigit: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ownerCode: string
  @column()
  declare serialNumber: string
  @column()
  declare sizeType: string
  @column()
  declare typeGroup: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'id', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserAssignedRoleSchema extends BaseModel {
  static $columns = ['assignedById', 'createdAt', 'expiresAt', 'isActive', 'roleId', 'userId'] as const
  $columns = UserAssignedRoleSchema.$columns
  @column()
  declare assignedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare isActive: boolean
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
