/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountUserSchema extends BaseModel {
  static $columns = ['accountId', 'userId'] as const
  $columns = AccountUserSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare userId: number
}

export class AccountSchema extends BaseModel {
  static $columns = ['billingAddressId', 'companyName', 'createdAt', 'creditTerms', 'id', 'registrationNumber', 'status', 'type', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare billingAddressId: number | null
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare creditTerms: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare registrationNumber: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactDetailSchema extends BaseModel {
  static $columns = ['addressLine', 'country', 'createdAt', 'email', 'id', 'phone', 'updatedAt'] as const
  $columns = ContactDetailSchema.$columns
  @column()
  declare addressLine: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContainerSchema extends BaseModel {
  static $columns = ['categoryIndentifier', 'checkDigit', 'createdAt', 'id', 'ownerCode', 'serialNumber', 'sizeType', 'typeGroup', 'updatedAt'] as const
  $columns = ContainerSchema.$columns
  @column()
  declare categoryIndentifier: string
  @column()
  declare checkDigit: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ownerCode: string
  @column()
  declare serialNumber: string
  @column()
  declare sizeType: string
  @column()
  declare typeGroup: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PortCallSchema extends BaseModel {
  static $columns = ['ata', 'atd', 'createdAt', 'eta', 'etd', 'id', 'pilotageRequired', 'purpose', 'status', 'totalFees', 'updatedAt', 'vesselId'] as const
  $columns = PortCallSchema.$columns
  @column.dateTime()
  declare ata: DateTime | null
  @column.dateTime()
  declare atd: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare eta: DateTime
  @column.dateTime()
  declare etd: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pilotageRequired: boolean
  @column()
  declare purpose: string
  @column()
  declare status: string
  @column()
  declare totalFees: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vesselId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'id', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserAccountAssignedRoleSchema extends BaseModel {
  static $columns = ['assignedById', 'createdAt', 'expiresAt', 'roleId', 'userId'] as const
  $columns = UserAccountAssignedRoleSchema.$columns
  @column()
  declare assignedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class UserAccountRoleSchema extends BaseModel {
  static $columns = ['accountId', 'active', 'createdAt', 'id', 'slug', 'updatedAt'] as const
  $columns = UserAccountRoleSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserAssignedRoleSchema extends BaseModel {
  static $columns = ['assignedById', 'createdAt', 'expiresAt', 'isActive', 'roleId', 'userId'] as const
  $columns = UserAssignedRoleSchema.$columns
  @column()
  declare assignedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare isActive: boolean
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'firstName', 'id', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VesselSchema extends BaseModel {
  static $columns = ['beam', 'createdAt', 'flagState', 'grossTonnage', 'imoNumber', 'loa', 'maxDraft', 'name', 'portAgentId', 'shippingLineId', 'status', 'type', 'updatedAt'] as const
  $columns = VesselSchema.$columns
  @column()
  declare beam: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flagState: string
  @column()
  declare grossTonnage: number
  @column({ isPrimary: true })
  declare imoNumber: string
  @column()
  declare loa: number
  @column()
  declare maxDraft: number
  @column()
  declare name: string
  @column()
  declare portAgentId: number | null
  @column()
  declare shippingLineId: number | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class YardSlotSchema extends BaseModel {
  static $columns = ['bay', 'createdAt', 'id', 'maxStackHeight', 'ownership', 'owningAccountId', 'row', 'status', 'type', 'updatedAt'] as const
  $columns = YardSlotSchema.$columns
  @column()
  declare bay: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxStackHeight: number
  @column()
  declare ownership: string
  @column()
  declare owningAccountId: number | null
  @column()
  declare row: number
  @column()
  declare status: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
