export type PortCallStatus =
  | 'pending'
  | 'awaiting_account_approval'
  | 'scheduled'
  | 'mainifest_submitted'
  | 'reconciled'
  | 'at_anchorage'
  | 'berthed'
  | 'operations_complete'
  | 'awaiting_outbound_cargo'
  | 'departed'
  | 'hold'
  | 'canceled'
  | 'delayed'
  | 'unable_to_accept'
